# Site settings
title: Michael Lam 
header-img: img/home-bg.jpg
email: lamm@eecs.oregonstate.edu
description: "Blog of a graduate student studying computer vision and machine learning."
baseurl: ""
url: "http://michaelqtlam.com"
github_username:  mqtlam

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
